# vmss-run-blob-tests.yml
---
- name: "Run Blob Tests"
  hosts: control
  vars:
    admin_username: sysadmin
    jar_file: "blob-tester-v12-1.0-jar-with-dependencies.jar"
    download_path: "downloads"
    storage_connection_string: "{{ AZURE_STORAGE_CONNECTION_STRING }}"
  tasks:
    - name: Create Downloads directory if it does not exist
      ansible.builtin.file:
        path: "/home/{{ admin_username }}/{{ download_path }}"
        state: directory
        mode: 0755
    - name: Run Blob Tests
      shell: |
        export AZURE_STORAGE_CONNECTION_STRING="{{ storage_connection_string }}"
        export TEST_MODE=DownloadOnly
        export CONTAINER_NAME ="blob-tests"
        export DOWNLOAD_PATH="/home/{{ admin_username }}/{{ download_path }}"
        java -jar /home/{{ admin_username }}/{{ jar_file }}
