# vmss-setup-deploy.yml
---
- name: "VMSS Setup & Deploy Artifacts"
  hosts: control
  become: yes
  vars:
    cert_src: "{{ cert_src }}"
    cert_file: "{{ cert_file }}"
    admin_username: sysadmin
    admin_password: "{{ admin_password }}"
    zip_src: "https://github.com/roberto-mardeni/azure-blob-tester-java/releases/download/1.0/jar-with-dependencies.zip"
    zip_file: "jar-with-dependencies.zip"
    jar_file: "blob-tester-v12-1.0-jar-with-dependencies.jar"
  tasks:
    - name: Install APT Packages
      apt:
        pkg:
        - default-jre
        - unzip
        update_cache: yes

    - name: Copy Azure Stack Certificate
      shell: |
        if [ -f "{{ cert_file }}" ] ; then
            rm "{{ cert_file }}"
        fi
        wget --no-check-certificate {{ cert_src }} > {{ cert_file }}

    - name: Install Azure Stack Certificate in Java Store
      community.general.java_cert:
        cert_alias: "ASH"
        cert_path: "/home/{{ admin_username }}/{{ cert_file }}"
        keystore_path: "/etc/ssl/certs/java/cacerts"
        keystore_type: "JCEKS"
        keystore_pass: changeit
        state: present
        trust_cacert: yes

    - name: Copy JAR ZIP file
      copy:
        src: "{{ zip_src }}"
        remote_src: yes
        dest: "/home/{{ admin_username }}/{{ zip_file }}"
        force: yes
        mode: 0755

    - name: Unzip JAR ZIP file
      args:
        chdir: "/home/{{ admin_username }}/"
      shell: |
        unzip {{ zip_file }}
