# vmss-setup-deploy.yml
---
- name: "VMSS Setup & Deploy Artifacts"
  hosts: nodes
  become: yes
  vars:
    cert_src: "{{ cert_src }}"
    cert_file: "{{ cert_file }}"
    ansible_username: sysadmin
    ansible_password: "{{ ansible_password }}"
    zip_src: "https://github.com/roberto-mardeni/azure-blob-tester-java/releases/download/1.0/jar-with-dependencies.zip"
    zip_file: "jar-with-dependencies.zip"
    jar_file: "blob-tester-v12-1.0-jar-with-dependencies.jar"
  tasks:
    - name: Install APT Packages
      ansible.builtin.apt:
        pkg:
        - default-jre
        - unzip
        update_cache: yes

    - name: Copy Azure Stack Certificate
      ansible.builtin.get_url:
        url: "{{ cert_src }}"
        dest: "/home/{{ ansible_username }}/{{ cert_file }}"
        validate_certs: no
        mode: 0644
        force: yes

    - name: Install Azure Stack Certificate in Java Store
      community.general.java_cert:
        cert_alias: "ASH"
        cert_path: "/home/{{ ansible_username }}/{{ cert_file }}"
        keystore_path: "/etc/ssl/certs/java/cacerts"
        keystore_pass: changeit
        state: present
        trust_cacert: yes

    - name: Copy JAR ZIP file
      ansible.builtin.get_url:
        url: "{{ zip_src }}"
        dest: "/home/{{ ansible_username }}/{{ zip_file }}"
        mode: 0644
        force: yes

    - name: Unzip JAR ZIP file
      ansible.builtin.unarchive:
        src: "/home/{{ ansible_username }}/{{ zip_file }}"
        dest: "/home/{{ ansible_username }}/"
        mode: 0755
