# vmss-setup-deploy.yml
---
- name: "VMSS Setup & Deploy Artifacts"
  hosts: nodes
  become: yes
  vars:
    ansible_username: sysadmin
    ansible_password: "{{ ansible_password }}"
    zip_src: "https://github.com/roberto-mardeni/azure-blob-tester-java/releases/download/1.0/jar-with-dependencies.zip"
    zip_file: "jar-with-dependencies.zip"
    jar_file: "blob-tester-v12-1.0-jar-with-dependencies.jar"
  tasks:
    - name: Install APT Packages
      ansible.builtin.apt:
        pkg:
        - default-jre
        - unzip
        update_cache: yes

    - name: Copy JAR ZIP file
      ansible.builtin.get_url:
        url: "{{ zip_src }}"
        dest: "/home/{{ ansible_username }}/{{ zip_file }}"
        mode: 0644
        force: yes

    - name: Unzip JAR ZIP file
      ansible.builtin.unarchive:
        src: "/home/{{ ansible_username }}/{{ zip_file }}"
        dest: "/home/{{ ansible_username }}/"
        mode: 0755
