name: Blob Tests in Azure Stack Hub

on:
  push:
    branches: [ main ]
    paths:
    - '.github/workflows/azure_stack_tests.yml'
    - 'ansible/**'

jobs:
  build:
    runs-on: ash-vm
    steps:
      - uses: actions/checkout@v2
      - name: Setup Machine
        working-directory: ansible
        run: |
          ansible-playbook --connection=local 127.0.0.1 vmss-setup-deploy.yml --extra-vars "cert_src={{ secrets.CERT_SRC }} cert_file={{ secrets.CERT_FILE }} admin_password={{ secrets.ADMIN_PASSWORD }}"
      - name: Run Tests
        working-directory: ansible
        run: |
          ansible-playbook --connection=local 127.0.0.1 vmss-run-blob-tests.yml --extra-vars "AZURE_STORAGE_CONNECTION_STRING={{ secrets.PREMIUM_STORAGE_CONNECTION_STRING }}"
