name: Blob Tests in Azure Stack Hub

on:
  push:
    branches: [ main ]
    paths:
    - '.github/workflows/azure_stack_tests.yml'
    - 'ansible/**'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Setup Machine
        run: ansible-playbook ansible/vmss-setup-deploy.yml
      - name: Run Tests
        run: ansible-playbook ansible/vmss-run-blob-tests.yml
